FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7
COPY ./app /app
WORKDIR /app
RUN pip install sklearn joblib
RUN pip install pandas	
RUN pip install numpy
RUN pip install matplotlib	
RUN pip install sklearn	
RUN pip install scipy	
RUN pip install nltk	
RUN pip install wordcloud	
RUN pip install datetime 	
RUN pip install tqdm	
RUN pip install gensim
